services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: gimli
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gimli_postgres_data:/var/lib/postgresql/data

volumes:
  gimli_postgres_data:
