<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Gimli.Infrastructure.Adapter.Notifications</AssemblyName>
    <RootNamespace>Gimli.Infrastructure.Adapter.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.Contracts\Application.Contracts.csproj" />
  </ItemGroup>
</Project>
