<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>InteriorMarketplace.Application</AssemblyName>
    <RootNamespace>InteriorMarketplace.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain\Domain.csproj" />
    <ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
  </ItemGroup>
</Project>
