using System.IdentityModel.Tokens.Jwt;using System.Security.Claims;using System.Text;using FluentValidation;using InteriorMarketplace.BuildingBlocks.Application;using InteriorMarketplace.Modules.Identity;using InteriorMarketplace.Modules.Notifications;using InteriorMarketplace.Modules.Projects.Adapters.Inbound;using InteriorMarketplace.Modules.Projects.Adapters.Outbound;using InteriorMarketplace.Modules.Projects.Application;using InteriorMarketplace.Modules.Projects.Domain;using InteriorMarketplace.Modules.VendorOffers.Adapters.Inbound;using InteriorMarketplace.Modules.VendorOffers.Application;using Microsoft.AspNetCore.Authentication.JwtBearer;using Microsoft.AspNetCore.Diagnostics;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using Microsoft.IdentityModel.Tokens;
var builder=WebApplication.CreateBuilder(args);var key=builder.Configuration["Jwt:Key"]??"development-only-secret-key-change-me-123456";
builder.Services.AddProblemDetails();builder.Services.AddHttpContextAccessor();builder.Services.AddOpenApi();builder.Services.AddEndpointsApiExplorer();builder.Services.AddSwaggerGen();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>o.TokenValidationParameters=new(){ValidateIssuer=true,ValidateAudience=true,ValidateLifetime=true,ValidateIssuerSigningKey=true,ValidIssuer="InteriorMarketplace",ValidAudience="InteriorMarketplace",IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key))});builder.Services.AddAuthorization();
builder.Services.AddDbContext<MarketplaceDbContext>(o=>o.UseNpgsql(builder.Configuration.GetConnectionString("Marketplace")));builder.Services.AddScoped<IProjectRepository,ProjectRepository>();builder.Services.AddScoped<IOfferRepository,OfferRepository>();builder.Services.AddScoped<ProjectService>();builder.Services.AddScoped<OfferService>();builder.Services.AddScoped<ICurrentUser,HttpCurrentUser>();builder.Services.AddSingleton<IClock,SystemClock>();builder.Services.AddScoped<INotificationPort,LoggingNotificationAdapter>();builder.Services.AddSingleton<IImageStorage>(_=>new LocalImageStorage(Path.Combine(builder.Environment.ContentRootPath,"wwwroot","images")));builder.Services.AddValidatorsFromAssemblyContaining<ProjectRequestValidator>();builder.Services.AddValidatorsFromAssemblyContaining<OfferRequestValidator>();
var app=builder.Build();app.UseExceptionHandler(handler=>handler.Run(async context=>{var error=context.Features.Get<IExceptionHandlerFeature>()!.Error;var status=error switch{KeyNotFoundException=>404,UnauthorizedAccessException=>403,ArgumentException=>400,InvalidOperationException=>409,_=>500};await Results.Problem(new ProblemDetails{Status=status,Title="Request failed",Detail=error.Message}).ExecuteAsync(context);}));app.UseStaticFiles();app.UseAuthentication();app.UseAuthorization();app.MapOpenApi();app.UseSwagger();app.UseSwaggerUI();
app.MapPost("/api/auth/dev-token",(DevTokenRequest request)=>{var user=request.Role.Equals("Vendor",StringComparison.OrdinalIgnoreCase)?SeedUsers.VendorId:SeedUsers.HomeownerId;var claims=new[]{new Claim(ClaimTypes.NameIdentifier,user.ToString()),new Claim(ClaimTypes.Role,request.Role)};var token=new JwtSecurityToken("InteriorMarketplace","InteriorMarketplace",claims,expires:DateTime.UtcNow.AddHours(8),signingCredentials:new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),SecurityAlgorithms.HmacSha256));return Results.Ok(new{accessToken=new JwtSecurityTokenHandler().WriteToken(token),userId=user});}).AllowAnonymous();app.MapProjectEndpoints();app.MapOfferEndpoints();await SeedAsync(app.Services);app.Run();
static async Task SeedAsync(IServiceProvider services){await using var scope=services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<MarketplaceDbContext>();await db.Database.MigrateAsync();if(await db.Projects.AnyAsync())return;var p=new Project(new(Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")),SeedUsers.HomeownerId,"نشیمن مدرن نمونه","https://images.example.local/sample-living-room.jpg",DateTime.UtcNow);p.AddElement("Sofa","مبل سه‌نفره","پارچه‌ای","220×90 cm","کرم",45000000,new(.10m,.45m,.42m,.35m));p.AddElement("Rug","فرش مدرن",null,"300×200 cm","طوسی",18000000,new(.20m,.72m,.55m,.20m));p.AddElement("FloorLamp","آباژور ایستاده",null,"160 cm","مشکی",8000000,new(.78m,.25m,.12m,.55m));p.Publish(DateTime.UtcNow);db.Projects.Add(p);await db.SaveChangesAsync();}
public sealed record DevTokenRequest(string Role);public partial class Program;
