<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Gimli.Application.UnitTests</AssemblyName>
    <RootNamespace>Gimli.Application.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Application\Application.csproj" />
  </ItemGroup>
</Project>
